import * as THREE from 'three'

/**
 * Build a 2D heightmap grid from BufferGeometry for fast Z lookup.
 * Geometry is expected in THREE space: X/Z are horizontal, Y is elevation.
 */
function buildHeightGrid(geo, gridRes) {
  const pos = geo.attributes.position
  const bbox = new THREE.Box3().setFromBufferAttribute(pos)

  const rangeX = bbox.max.x - bbox.min.x || 1
  const rangeZ = bbox.max.z - bbox.min.z || 1

  const grid = new Float32Array(gridRes * gridRes).fill(bbox.min.y)

  for (let i = 0; i < pos.count; i++) {
    const x = pos.getX(i)
    const y = pos.getY(i)
    const z = pos.getZ(i)

    const ix = Math.round(((x - bbox.min.x) / rangeX) * (gridRes - 1))
    const iz = Math.round(((z - bbox.min.z) / rangeZ) * (gridRes - 1))
    const idx = Math.min(iz, gridRes - 1) * gridRes + Math.min(ix, gridRes - 1)

    // keep highest point so the cutter respects peaks
    if (y > grid[idx]) grid[idx] = y
  }

  return { grid, bbox, rangeX, rangeZ }
}

function sampleHeight(grid, gridRes, bbox, rangeX, rangeZ, xMm, yMm, scaleH) {
  // xMm / yMm are in output-mm space (0..scaleXY)
  const fx = (xMm / (rangeX * scaleH)) * (gridRes - 1)
  const fz = (yMm / (rangeZ * scaleH)) * (gridRes - 1)
  const ix0 = Math.max(0, Math.min(gridRes - 2, Math.floor(fx)))
  const iz0 = Math.max(0, Math.min(gridRes - 2, Math.floor(fz)))
  const tx = fx - ix0
  const tz = fz - iz0
  const h00 = grid[ iz0      * gridRes + ix0    ]
  const h10 = grid[ iz0      * gridRes + ix0 + 1]
  const h01 = grid[(iz0 + 1) * gridRes + ix0    ]
  const h11 = grid[(iz0 + 1) * gridRes + ix0 + 1]
  return h00 * (1 - tx) * (1 - tz)
       + h10 *      tx  * (1 - tz)
       + h01 * (1 - tx) *      tz
       + h11 *      tx  *      tz
}

/**
 * Generate a raster-scan G-code toolpath from a THREE.BufferGeometry.
 *
 * Coordinate mapping:
 *   THREE X  → G-code X (horizontal)
 *   THREE Z  → G-code Y (horizontal, row axis)
 *   THREE Y  → G-code Z (inverted: high terrain = shallow cut near 0,
 *                         low terrain = deep cut toward -maxDepth)
 *
 * @param {THREE.BufferGeometry} geometry
 * @param {{
 *   feedRate: number,
 *   plungeRate: number,
 *   safeZ: number,
 *   toolDiameter: number,
 *   stepover: number,
 *   maxDepth: number,
 *   scaleXY: number,
 * }} settings
 * @returns {string}
 */
export function generateGcode(geometry, settings) {
  const {
    feedRate    = 1000,
    plungeRate  = 300,
    safeZ       = 5,
    toolDiameter = 3.175,
    stepover    = 0.5,
    maxDepth    = 10,
    scaleXY     = 100,
  } = settings

  // Work on a non-indexed clone so every vertex is explicit
  let geo = geometry.clone()
  if (geo.index) geo = geo.toNonIndexed()

  const GRID_RES = Math.max(32, Math.round(Math.sqrt(geo.attributes.position.count)))
  const { grid, bbox, rangeX, rangeZ } = buildHeightGrid(geo, GRID_RES)
  geo.dispose()

  const minY = bbox.min.y
  const maxY = bbox.max.y
  const elevRange = maxY - minY || 1

  // Scale factor: fit the larger horizontal dimension to scaleXY mm
  const scaleH = scaleXY / Math.max(rangeX, rangeZ)
  const xWidth = rangeX * scaleH   // output width in mm
  const yDepth = rangeZ * scaleH   // output height (Y axis) in mm

  // Map THREE-Y elevation to G-code Z:
  //   maxY (peaks)  → 0            (tool just skims surface)
  //   minY (valleys)→ -maxDepth    (tool cuts deepest)
  function elevToGcodeZ(threeY) {
    const t = (threeY - minY) / elevRange   // 0 = valley, 1 = peak
    return ((t - 1) * maxDepth).toFixed(3)
  }

  function sample(xMm, yMm) {
    return sampleHeight(grid, GRID_RES, bbox, rangeX, rangeZ, xMm, yMm, scaleH)
  }

  const rowStep  = toolDiameter * stepover          // mm between rows
  const colStep  = Math.max(rowStep / 2, 0.1)       // X resolution along each row

  const lines = []
  lines.push('; G-code generated by HuaTrienHao 3D')
  lines.push(`; Tool: ${toolDiameter}mm  Feed: ${feedRate}mm/min  Plunge: ${plungeRate}mm/min`)
  lines.push(`; Depth: ${maxDepth}mm  Size: ${xWidth.toFixed(1)}x${yDepth.toFixed(1)}mm`)
  lines.push('G21           ; metric')
  lines.push('G90           ; absolute positioning')
  lines.push(`G0 Z${safeZ.toFixed(3)}`)
  lines.push('G0 X0 Y0')
  lines.push('')

  let rowIndex = 0

  for (let y = 0; y <= yDepth + 1e-6; y += rowStep) {
    const yClamped = Math.min(y, yDepth)
    const leftToRight = rowIndex % 2 === 0

    const xStart = leftToRight ? 0        : xWidth
    const xEnd   = leftToRight ? xWidth   : 0
    const xDir   = leftToRight ? 1        : -1

    // Rapid to row start
    lines.push(`G0 X${xStart.toFixed(3)} Y${yClamped.toFixed(3)}`)
    lines.push(`G1 Z${elevToGcodeZ(sample(xStart, yClamped))} F${plungeRate}`)

    // Scan along X
    let x = xStart + xDir * colStep
    while (leftToRight ? x < xEnd : x > xEnd) {
      const xc = Math.max(0, Math.min(xWidth, x))
      lines.push(`G1 X${xc.toFixed(3)} Z${elevToGcodeZ(sample(xc, yClamped))} F${feedRate}`)
      x += xDir * colStep
    }

    // Ensure we reach the exact end of the row
    lines.push(`G1 X${xEnd.toFixed(3)} Z${elevToGcodeZ(sample(xEnd, yClamped))} F${feedRate}`)
    lines.push(`G0 Z${safeZ.toFixed(3)}`)

    rowIndex++
  }

  lines.push('')
  lines.push(`G0 Z${safeZ.toFixed(3)}`)
  lines.push('G0 X0 Y0')
  lines.push('M2            ; end program')

  return lines.join('\n')
}
